name: iControlU
main: pw.kaboom.icontrolu.Main
description: Plugin that allows players to control other players.
api-version: 1.13
version: master

commands:
   icu:
      description: Control another player's movements, inventory and chat
      permission: icu.command
